name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'dependencies'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'feature'
  patch:
    labels:
      - 'patch'
  default: patch
autolabeler:
  - label: 'enhancement'
    title:
      - '/feature/i'
      - '/feat/i'
      - '/enhancement/i'
  - label: 'bug'
    title:
      - '/fix/i'
      - '/bugfix/i'
      - '/bug/i'
template: |
  ## Changes

  $CHANGES

  ## Contributors

  $CONTRIBUTORS
