# dev deployment for firezone
version: '3.7'

volumes:
  postgres-data:

services:
  firezone:
    image: firezone/firezone:latest
    ports:
      - 51820:51820/udp
      - 13000:13000
    env_file:
      - docker.env
    volumes:
      - ./docker/firezone:/var/firezone
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.forwarding=1
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: firezone
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
