site_name: Firezone python client
site_author: msterhuj
site_description: >-
  A simple interface to manage firezone with its api

repo_name: firezone-client
repo_url: https://github.com/msterhuj/firezone-client
edit_uri: https://github.com/msterhuj/firezone-client

nav:
  - Getting Started: index.md
  - Configuration: reference/configuration.md
  - User: reference/user.md
  - Rule: reference/rule.md
  - Device: reference/device.md
  - Utils: utils.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

theme:
  name: material

  palette:
    primary: deep orange

  icon:
    repo: fontawesome/brands/github

  features: []
