name: Run unittest

on:
  workflow_dispatch:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "./docker-compose.yml"
      - name: Migrate firezone database
        run: docker compose run --rm firezone bin/migrate
      - name: Create admin
        run: docker compose run --rm firezone bin/create-or-reset-admin
      - name: Create API token
        run: docker compose exec firezone bin/create-api-token > .token
